version: "3.9"
services:
  registry:
    image: registry:latest
    container_name: registry
    restart: always
    ports:
      - 443:443
    volumes:
      - /mnt/docker-registry-images:/var/lib/registry
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /var/lib/registry/certs/STAR_kyros_com_br.crt
      REGISTRY_HTTP_TLS_KEY: /var/lib/registry/certs/STAR_kyros_com_br.key
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/auth/htpasswd
      REGISTRY_AUTH: htpasswd